export const subjectsSelect = [
    'Accounting',
    'Advanced Mathematics',
    'Art and Craft',
    'Art and Design',
    'Basic Math - Counting',
    'Biology',
    'Business Studies',
    'Career and Technical Education',
    'Chemistry',
    'Civics',
    'Computer Science',
    'Economics',
    'English Language',
    'English Literature',
    'Environmental Management',
    'French',
    'Geography',
    'German',
    'Government',
    'Health Education',
    'History',
    'Home Economics (Cooking)',
    'Home Economics (Sewing)',
    'Information and Communication Technology - ICT',
    'Language Development',
    'Mathematics',
    'Moral Education or Ethics',
    'Music and Movement',
    'Physical Education',
    'Physics',
    'Psychology',
    'Science',
    'Social Skills',
    'Social Studies',
    'Sociology',
    'Spanish',
    'Storytime',
  ].map((subject) => ({ value: subject.toLowerCase(), label: subject.toUpperCase() }));
  